### ISSUE TITLE
Spades.shiny to available for R version 3.6.1

### ISSUE THREAD

**Issue by crosbya1** [PredictiveEcology/SpaDES.shiny#104]
> install.packages("SpaDES.shiny")
Installing package into ‘.../Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘SpaDES.shiny’ is not available (for R version 3.6.1)

**Comment by achubaty** [comment]
`SpaDES.shiny` is not yet on CRAN, but you can install it using:

```r
devtools::install_github("PredictiveEcology/SpaDES.shiny")
```
