### ISSUE TITLE
Module: Exporting data.

### ISSUE THREAD

**Issue by mateuszwyszynski** [PredictiveEcology/SpaDES.shiny#17]

**Comment by mateuszwyszynski** [comment]
@eliotmcintire @achubaty - Could you please tell us:
1. What types of data you would like to be able to export
2. Is there any place in the current LandWeb app where such export takes place?

**Comment by achubaty** [comment]
Data to export could be:

1. raster maps -- these should be exportable as different file types (e.g., tiff, grd, rds/rdata, etc.) so the user will need to be able to select the filetype from a list.
2. `Spatial*` objects (e.g., polygons)
3. plots of maps (e.g., polygons overlaid on rasters) or summary figures/graphs (e.g., histograms, etc.)
4. `simList` objects (this is low priority as this is an advanced use case)

We haven't implemented saving spatial/raster data types in the current apps.
Exporting figures is fairly easy using `ggplot2::ggsave` for ggplots. I believe don't have this implemented in the current app.

**Comment by achubaty** [comment]
this is app-specific, but has been for LandWeb
