### ISSUE TITLE
Improve the generator to use provided modules.

### ISSUE THREAD

**Issue by DamianRodziewicz** [PredictiveEcology/SpaDES.shiny#29]

**Comment by DamianRodziewicz** [comment]
@achubaty @eliotmcintire - in the code I see that you use `return()` when returning values from functions. According to the style guide we use we are not writing `return()` explicitly. Would you rather we did write `return()` everywhere we return a value from a function?

**Comment by achubaty** [comment]
Yes, please. That would be my preference.

**Comment by DamianRodziewicz** [comment]
https://github.com/PredictiveEcology/SpaDES.shiny/pull/51
