### ISSUE TITLE
Restrict merging code without pull requests for develop branch

### ISSUE THREAD

**Issue by DamianRodziewicz** [PredictiveEcology/SpaDES.shiny#31]

**Comment by DamianRodziewicz** [comment]
@achubaty @eliotmcintire - please change 'develop' branch settings as per below (replacing master with develop)

1. Choose 'develop' branch
![image](https://user-images.githubusercontent.com/4648934/30274672-b7ac51b2-96fe-11e7-9198-040bdad7d2ea.png)

2. Check the checkboxes
![image](https://user-images.githubusercontent.com/4648934/30274630-944d9e4c-96fe-11e7-9d36-5817d18a1406.png)

**Comment by achubaty** [comment]
done
