### ISSUE TITLE
Create a module which adds (summary) popups

### ISSUE THREAD

**Issue by mateuszwyszynski** [PredictiveEcology/SpaDES.shiny#48]

**Comment by mateuszwyszynski** [comment]
@eliotmcintire @achubaty 

As I understand, currently in LadnWeb app popups summary includes information from two different sets of polygons. One set is from `ecodistricts.shp` shapefile and one is from `shpLandWEB.shp`. Is that correct?

In the end we would like to allow a user to choose any set of polygons on a map. Hence, there is a question whether you would like popups to still include information retrieved from different sets of polygons at the same time? Or, rather, have a popup which summarizes over one (current) set of polygons and so the user can see the information connected with the other polygons by changing the underlaying polygons.

I believe the second solution is more transparent from users perspective, because it is clear what information they are currently dealing with.

**Comment by achubaty** [comment]
Yes, summarizing over one current set makes the most sense.

**Comment by achubaty** [comment]
closing this now that the corresponding PR is merged into `develop`
