### ISSUE TITLE
Initial design of the generator and how application structure is generated.

### ISSUE THREAD

**Issue by DamianRodziewicz** [PredictiveEcology/SpaDES.shiny#8]
Initial design doc: https://docs.google.com/document/d/1IPA6upO4meF3UseP-FiXcM1eksu31o84rEiipdnv2Q4/edit

**Comment by DamianRodziewicz** [comment]
During the design sessions we came across an idea to actually have two separate packages - one for the app generator which can be domain agnostic (i.e. doesn't have to rely on SpaDES.shiny) and the other one that contains all the modules. By default we could import SpaDES.shiny in the generator code. That's just a thought and we are not going to do this yet - however it's something that we can keep in our heads.

**Comment by DamianRodziewicz** [comment]
@eliotmcintire @achubaty - there are two approaches we can choose from:

Example use case: spaDES.shiny has a slider module and export module. I would like to create an app that on one page has UI that allows user to select N with slider, click export button and get N random numbers in csv.

1. The level of abstraction that user works on when writing metadata for the app is shiny module. Each menu item corresponds to one shiny module - this means that when user bootstraps app he has to write:

```
app_metadata <- bind_rows(
  list(
    menu_item = "Export random set",
    tab_item = "random_set_export",
    object_names = "random_set_export",
    subheading = "",
    content = customShinyModule("random_set_export_module")
    // OR 1.1 - assuming there exists a separate module in spaDES.shiny that does exactly that and is called "random_set_export_module"
    content = shinyModule("random_set_export_module")
  )
)
```

This would generate a shiny app that contains a file `random_set_export_module.R` which contains a dummy module which is already hooked up in the app. Inside of this module user has to use the modules from SpaDES.shiny to implement the page that he wants.

2. Generator allows user to specify more detailed UI (OR specify what modules he wants to include within his new module), for example:
```
app_metadata <- bind_rows(
  list(
    menu_item = "Export random set",
    tab_item = "random_set_export",
    object_names = "random_set_export",
    subheading = "",
    content = list( // or maybe a bit more complex structure that defines the content in a more detailed way.
        shinyModule("slider"), // from SpaDES.shiny
        shinyModule("export") // from SpaDES.shiny
    )
    // OR 2.1
    content = customShinyModule("random_set_export_module", include = list(
        shinyModule("slider"), // from SpaDES.shiny
        shinyModule("export") // from SpaDES.shiny
    )
  )
)
```

Which would either generate an app that displays slider and export button and in code there is no clear abstraction level that says "one menu item = one module".
OR 2.1 This would generate an app that displays slider and export button and in code user has a `random_set_export_module.R` file that already uses the two modules in a simple way. User has to edit that code to connect slider with export.

@eliotmcintire @achubaty I hope the above is understandable, please let me know if you'd like a better clarification of what I mean. I think that option 2.1 or 1 or 1.1 are the ones to choose from. I'd go with option 1 or 1.1. This means that we require user to always work with shiny modules and if there is no module that does exactly what he wants he has to write it himself and either make it generic and push to SpaDES.shiny as a new module or just keep it in his own app.

**Comment by DamianRodziewicz** [comment]
From our understanding of the scope option 1 is the one that has been decided. Just wanted to confirm that this is the case.

**Comment by DamianRodziewicz** [comment]
I'm closing this issue as the initial design has been finished. We'll get back to this question once it is answered and will update the doc accordingly

**Comment by achubaty** [comment]
> During the design sessions we came across an idea to actually have two separate packages - one for the app generator which can be domain agnostic (i.e. doesn't have to rely on SpaDES.shiny) and the other one that contains all the modules. By default we could import SpaDES.shiny in the generator code. That's just a thought and we are not going to do this yet - however it's something that we can keep in our heads.

Yes, in our initial attempts at this, we had decided that it was easiest to keep the 'generator' in a separate package, so I think that's OK here. We can discuss whether this is (or will become) strictly necessary, or if it's simply easier to work with and maintain 2 packages.

**Comment by achubaty** [comment]
> From our understanding of the scope option 1 is the one that has been decided. Just wanted to confirm that this is the case.

Yes, I think that option 1 makes a good starting point.

**Comment by eliotmcintire** [comment]
I think 1 & 1.1 are good. There should be some modules that can be used off the shelf, and others that will need customizing (some to lots).
