### ISSUE TITLE
generalize code within clumpMod2

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.shiny#97]
_From @achubaty on March 12, 2018 19:37_

_Copied from original issue: eliotmcintire/LandWeb#18_

**Comment by achubaty** [comment]
can we pull this and `largePatches` out of the package and keep it in LandWeb? it's fairly specialized, and currently relies on global variables set in LandWeb (`LandWebVersion`)!!

**Comment by eliotmcintire** [comment]
I suspect we can for now. The general point is some GIS operations with
histogram summaries... That should be useful down the road for other
similar situations.

**Comment by achubaty** [comment]
there's currently too much dependence on LandWeb, including `largePatchesFn`, so I have moved these out of the package in bfee5dd0c2728b025eaa265cca6a84dc7707d5ec
